### PR TITLE
Use babel-core

### PR DESCRIPTION
**Pull request by alexwilson**
Using @LoganBarnett's changes, allow compatibility with Babel 6.

### CODE REVIEW

**Comment by alexwilson** [comment]
Note: this is a breaking change so I would definitely tag this with a semvar denoting as such.

**Comment by kossnocorp** [comment]
@antoligy thanks, will do!

**Comment by kossnocorp** [comment]
Published as `babel-hubot@0.2.0`

**Comment by alexwilson** [comment]
Awesome, thanks! :smile:

**Pull request merged**
